arm: # 그룹 이름은 그대로 유지
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.005 # 필요하면 시간을 조금 늘려도 됩니다 (예: 0.05)
  solve_type: Speed # 옵션: Speed, Distance, Manipulation1, Manipulation2
