# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - zero_arm_controller
    - hand_controller

  zero_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - joint6
    action_ns: gripper_cmd
    default: true